version: '3'

services:
    web:
        build: 
            context: .
        volumes:
            - .:/code
        command: gunicorn --daemon --workers 3 --bind unix:/home/cuttice/dockerproject/docker/app-version3/personalapp.sock personalapp.wsgi



        ports:
            - "8000:8000"
        depends_on:
            - db
           
    db:
       image: postgres:10.1-alpine
       volumes:
           - postgres_data:/var/lib/postgresql/data/
       environment:
           - POSTGRES_USER=personalapp
           - POSTGRES_PASSWORD=hello
           - POSTGRES_DB=hello


volumes:
  postgres_data:      