version: 1

# jobs refer to a single execution of the build
jobs:
  # build is the name of the job....they can be multiple and unique
  build:
    # builds occur in a docker container
    docker:
      - image: circleci/python:3.7
    #     environment: # environment variables for primary container
    #       DATABASE_URL: postgresql://root@localhost/hello?sslmode=disable
    #   # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
    #   - image: circleci/postgres:9.6.2
    #     environment: # environment variables for the Postgres container.
    #       POSTGRES_USER: personalapp
    #       POSTGRES_DB: hello
    # working_directory: ~/byob-profiles-rest-api

    # series/ list of steps done for the build
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pip install --upgrade pip
            python3 -m venv dockerproject
            . dockerproject/bin/activate
            pip3 install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . dockerproject/bin/activate
            coverage run --source='.' manage.py test
            coverage report
