version: 2
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

# jobs refer to a single execution of the build
jobs:
  # build is the name of the job....they can be multiple and unique
  build:
    # builds occur in a docker container
    docker:
      - image: circleci/python:3.7
    steps:
      # Step 1: obtain repo from GitHub
      -checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pip install --upgrade pip
            python3 -m venv dockerproject
            . dockerproject/bin/activate
            pip3 install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . dockerproject/bin/activate
            coverage run --source='.' manage.py test
            coverage report
      - run:
          name: verify git tag vs. version
          command: |
            . dockerproject/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = odhiambocuttice" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            make package
      - run:
          name: upload to pypi
          command: |
            . dockerproject/bin/activate
            twine upload dist/*