---

- hosts: all
  vars_files:
    - vars.yml
  become: yes

  tasks:
    - name: Install System Packages
      apt: name={{ item }} update-cache=yes
      with_items: "{{ system_packages }}"

    - name: Create directory for project
      file: path={{ install_root }}/{{ project_name }} state=directory

    - name: Ensure postgresql server is runing
      service: name=postgresql state=started

    - name: Create db
      become_user: postgres
      postgresql_db: name={{ db_name }}

    - name: Create db user
      become_user: postgres
      postgresql_db: db={{ db_name}} name={{ db_user }} login_password={{ db_password}} 

    - name: Remove default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent

