---

  - hosts: all
  
    become: yes
   
    tasks:
      - name: Create file
        copy:
          src: /home/cuttice/add.py

          dest: /dockerproject
     
      - name: Install dependancies
        apt: name={{ item }} state=installed
        with_items:
          - python3-setuptools
          - python3-dev
          - build-essential
          - python3-pip
          - flake8

      - name: Install virtualenv
        pip:
          name: virtualenv
          executable: pip

      - name: install django
        pip:
          name: django
      - name: install prometheus
        pip:
          name: django-prometheus ==1.0.15
      - name: gunicorn
        pip:
          name: gunicorn
      - name: pyscopg
        pip:
          name: psycopg2-binary

      - name: coffee-app-list
        pip:
          name: coffee-list-app==1.0.15
  
      
      # - name: install basic packages
      #   action: >
      #     {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
      #   with_items:
      #     - vim
      #     - tmux
      #     - coffee-app-list
        